[package]
name = "test_ex"
version = "0.1.0"
authors = ["Vadim Smirnov <smirnovvad7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.12"
tokio = {version = "1.2.0", features = ["full"]}
